return {
	"WhoIsSethDaniel/mason-tool-installer.nvim",
	opts = {
		"ansiblels",
		"ansible-lint",
		"clangd",
		"clang_format",
		"cpplint",
		"bashls",
		"docker_compose_language_service",
		"go-debug-adapter",
		"gofumpt",
		"goimports",
		"golangci-lint",
		"golangci-lint-langserver",
		"gopls",
		"marksman",
		"rust_analyzer",
		"stylua",
		"lua_ls",
	},
}
